name: Pymeasure CI
on: 
  push:
    branches: 
      - master
      - develop
  pull_request:

jobs:
  docs_lint:
    name: Docs and Linting
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      max-parallel: 4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install docs dependencies
        run: |
          pip install wheel
          pip install -r requirements/pymeasure_readthedocs.txt
          pip install sphinx sphinx_rtd_theme flake8
      - name: Lint with flake8
        continue-on-error: true
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Generate docs
        working-directory: ./docs
        run: |
          echo "::add-matcher::.github/sphinx.json"
          make html
      - name: Run doctests
        working-directory: ./docs
        run: |
          echo "::add-matcher::.github/sphinx.json"
          make doctest
  test:
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }}
    needs: docs_lint  # no need to continue if the docs/lint job fails
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:    
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: py${{ matrix.python-version }}-${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/pymeasure.yml') }}
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: requirements/pymeasure.yml
          activate-environment: pymeasure
          use-only-tar-bz2: true  # for caching to work properly
      - name: Install CI dependencies
        shell: bash -l {0}
        run: conda install conda-build flake8
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Build pymeasure
        shell: bash -l {0}
        run: python setup.py bdist_wheel
      - name: Install pymeasure
        shell: bash -l {0}
        run: python -m pip install dist/*.whl
      - name: Pytest with xvfb
        shell: bash -l {0}
        if: runner.os == 'Linux'
        run: xvfb-run -a pytest
      - name: Pytest 
        shell: bash -l {0}
        if: runner.os != 'Linux'
        run: pytest
